# Hezkore's Alacritty settings
[window]
dimensions = { columns = 127, lines = 37 }
opacity = 0.99
resize_increments = true

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
mouse.mods = "Control"
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[bell]
animation = "EaseOutSine"
duration = 250
color = "#1e1f29"

[scrolling]
multiplier = 1

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
size = 13.5

[colors]
transparent_background_colors = true

[colors.primary]
background = "#1e1f29"

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"
